<?php

namespace AppBundle\Repository;

/**
 * AufgabeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AufgabeRepository extends \Doctrine\ORM\EntityRepository
{
}
